services:
  postgres:
    image: postgres:latest
    container_name: onlyjs-ecommerce
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlyjs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onlyjs-network

networks:
  onlyjs-network:
    driver: bridge

volumes:
  postgres_data:
